table DimProduct
	lineageTag: f2d5d1ed-98b4-4f37-b8e8-fa63489628fe

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 1309677c-c157-4e5a-a39a-34ac3954e46e
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: string
		lineageTag: 3e6b14ba-0abd-4b27-8f59-f9da20ca3d9d
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 8f6e27a5-022d-4338-943e-686e6f5e3415
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: d2f70d56-26ef-4df4-883b-9e72065eebc4
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column SubCategory
		dataType: string
		lineageTag: f1ee2feb-06e4-40af-a262-8826519f6bb9
		summarizeBy: none
		sourceColumn: SubCategory

		annotation SummarizationSetBy = Automatic

	column UnitCost
		dataType: double
		lineageTag: f1a9a9a9-361c-4056-b411-6734e23d13e8
		summarizeBy: none
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ListPrice
		dataType: double
		lineageTag: 4d8ad722-ea11-4751-aba8-dcc034b7ae92
		summarizeBy: none
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DimProduct = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("F:\kowluri\projects\PowerBI\SalesData_PowerBI.xlsx"), null, true),
				    DimProduct_Sheet = Source{[Item="DimProduct",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(DimProduct_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductID", type text}, {"ProductName", type text}, {"Category", type text}, {"SubCategory", type text}, {"UnitCost", type number}, {"ListPrice", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

